export { PgAirtableDb } from './lib/client';
export type { PgDatabase } from './lib/client';
export { getFirstFromPg } from './lib/pg-query';
export type { GetFirstFromPgOptions } from './lib/pg-query';
export {
  createTestPgClient, createTestAirtableClient, createTestDbClients, pushTestSchema, resetTestDb,
} from './lib/test-db';
export type { TestPgAirtableDb } from './lib/test-db';

export {
  metaTable,
  syncMetadataTable,
  syncRequestsTable,
  posthogEmittedEventsTable,
  exerciseResponsePgTable,
  courseTable,
  formConfigurationTable,
  personTable,
  sharedDemoOutputTable,
  blogTable,
  jobPostingTable,
  projectTable,
  missionTable,
  programTable,
  groupTable,
  groupSwitchingTable,
  groupDiscussionTable,
  meetPersonTable,
  zoomAccountTable,
  roundTable,
  applicationsRoundTable,
  meetCourseTable,
  chunkTable,
  unitTable,
  unitResourceTable,
  resourceTable,
  exerciseTable,
  applicationsCourseTable,
  courseRegistrationTable,
  selfServeCourseRegistrationTable,
  userTable,
  courseBuilderUserTable,
  resourceCompletionPgTable,
  facilitatorDiscussionSwitchingTable,
  dropoutTable,
  teamMemberTable,
  testimonialTable,
  rapidGrantTable,
  careerTransitionGrantTable,
  careerTransitionGrantApplicationTable,
  rapidGrantApplicationTable,
  oneOnOneAdvisingApplicationTable,
  bugReportsTable,
  courseFeedbackTable,
  peerFeedbackTable,
  vanityUrlsTable,
  RESOURCE_FEEDBACK,
  COURSE_ROLE,
  isDiscussionFacilitator,
  isDiscussionParticipant,
} from './schema';

// Type exports
export type {
  Meta,
  SyncMetadata,
  SyncRequest,
  SyncStatus,
  Course,
  ExerciseResponse,
  FormConfiguration,
  Person,
  SharedDemoOutput,
  Group,
  GroupDiscussion,
  GroupSwitching,
  MeetPerson,
  ZoomAccount,
  Round,
  ApplicationsRound,
  MeetCourse,
  Blog,
  JobPosting,
  Project,
  Mission,
  Program,
  Chunk,
  Unit,
  UnitResource,
  Resource,
  Exercise,
  ApplicationsCourse,
  CourseRegistration,
  SelfServeCourseRegistration,
  User,
  CourseBuilderUser,
  ResourceCompletion,
  FacilitatorSwitching,
  Dropout,
  TeamMember,
  Testimonial,
  RapidGrant,
  CareerTransitionGrant,
  CareerTransitionGrantApplication,
  RapidGrantApplication,
  OneOnOneAdvisingApplication,
  BugReport,
  CourseFeedback,
  PeerFeedback,
  VanityUrl,
} from './schema';

export { getPgAirtableFromIds, PgAirtableTable } from './lib/db-core';

export { AirtableTsError, ErrorType } from 'airtable-ts/dist/AirtableTsError';

// TODO: restrict what's exported
export * from 'drizzle-orm';
