name: Bug Report
description: Report a bug
title: "[Bug] Short descriptive title"
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: summary
    attributes:
      label: 🧩 Summary
      description: Briefly describe the bug in one or two sentences.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🛝 Steps to reproduce
      description: What steps can we take to reproduce the bug?
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: ✅ Definition of done
      description: What should be true or visible to consider this bug fixed?
      placeholder: A clear description of what you expect to see when the bug is fixed.
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: 📌 Notes / Designs
      description: Include Figma links, screenshots, or Loom walkthroughs.
      placeholder: Add any other context about the problem here.

    - type: dropdown
    id: priority
    attributes:
      label: Suggested Priority Level
      description: |
        What priority do you think this should have?
        
        • P0: Critical - Absolutely critical and requires immediate action
        • P1: High - Major issue for current sprint/release cycle (2-week sprint)
        • P2: Medium - Standard issue for a future release (default)
        • P3: Low - Minor issue/enhancement that can be postponed
        • P4: Trivial/Wishlist - Not a priority, may never be addressed
      options:
        - P2: Medium (Default)
        - P0: Critical
        - P1: High
        - P3: Low
        - P4: Trivial/Wishlist
      default: 0
    validations:
      required: true
