name: Design Issue
description: Create a design task or request
title: "[Design] Short descriptive title"
labels: [design]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating a design issue!

  - type: textarea
    id: summary
    attributes:
      label: 🎨 Summary
      description: Briefly describe the design task or request in one or two sentences.
      placeholder: A clear and concise description of what needs to be designed.
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: ✅ Definition of done
      description: What needs to be true for this design to be considered complete?
      placeholder: A clear description of the deliverables (e.g., Figma mockups, design system updates, prototype, etc.).
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: 📌 Notes / References
      description: Include Figma links, screenshots, inspiration, user research, or other relevant context.
      placeholder: Add any other context about the design request here.

  - type: dropdown
    id: priority
    attributes:
      label: Suggested Priority Level
      description: |
        What priority do you think this should have?
        
        • P0: Critical - Absolutely critical and requires immediate action
        • P1: High - Major issue for current sprint/release cycle (2-week sprint)
        • P2: Medium - Standard issue for a future release (default)
        • P3: Low - Minor issue/enhancement that can be postponed
        • P4: Trivial/Wishlist - Not a priority, may never be addressed
      options:
        - P2: Medium (Default)
        - P0: Critical
        - P1: High
        - P3: Low
        - P4: Trivial/Wishlist
      default: 0
    validations:
      required: true

