name: Feature Report
description: Suggest a new feature or document an idea
title: "[Feature] Short descriptive title"
labels: [feature, triage]
assignees: [bluebotimpact]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: summary
    attributes:
      label: 🧩 Summary
      description: Briefly describe the feature or idea in one or two sentences.
      placeholder: A clear and concise description of the feature you'd like to see.
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: ✅ Definition of done
      description: What needs to be true for this task to be considered complete?
      placeholder: A clear description of what needs to be implemented for this feature to be complete.
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: 📌 Notes / Designs
      description: Include Figma links, screenshots, or Loom walkthroughs.
      placeholder: Add any other context about the feature request here.

  - type: dropdown
    id: urgency
    attributes:
      label: How urgent is this?
      options:
        - 🔥 Today
        - 🕐 Within 1 week
        - 🧊 Non-urgent / backlog
      default: 🕐 Within 1 week
