import type { Meta, StoryObj } from '@storybook/react';
import { loggedInStory } from '@bluedot/ui/src/utils/storybook';
import { SidebarFacilitateAgainPanel } from './SidebarFacilitateAgainPanel';
import type { EligibleRoundsCourse } from '../../server/routers/facilitator-applications';
import { trpcStorybookMsw } from '../../__tests__/trpcMswSetup.browser';

const eligibleCourses: EligibleRoundsCourse[] = [
  {
    courseId: 'course-agi',
    courseTitle: 'AGI Strategy',
    courseSlug: 'agi-strategy',
    rounds: [
      {
        id: 'round-1',
        label: 'Week 28 Intensive',
        firstDiscussionDate: '2026-04-07',
        lastDiscussionDate: '2026-04-14',
      },
    ],
  },
];

const meta = {
  title: 'Courses/SidebarFacilitateAgainPanel',
  component: SidebarFacilitateAgainPanel,
  tags: ['autodocs'],
  parameters: {
    layout: 'padded',
    docs: {
      description: {
        component:
          'Pinned to the bottom of the course sidebar for facilitators wrapping up a cohort of this course. '
          + 'Links to the prefilled quick-apply form for the soonest open round, and renders nothing when the '
          + 'facilitator has no eligible round to apply to.',
      },
    },
  },
  // Match the 360px course sidebar so the CTA wraps and spaces as it does in product.
  // Inline width (not a Tailwind class) because arbitrary classes in story decorators
  // aren't reliably generated by Storybook's JIT.
  decorators: [(Story) => <div style={{ width: 360 }}><Story /></div>],
  args: { courseSlug: 'agi-strategy' },
  ...loggedInStory(),
} satisfies Meta<typeof SidebarFacilitateAgainPanel>;

export default meta;
type Story = StoryObj<typeof meta>;

// Facilitator wrapping up this course with an open round to apply to: the CTA renders.
export const Default: Story = {
  parameters: {
    msw: {
      handlers: [trpcStorybookMsw.facilitatorApplications.eligibleRounds.query(() => eligibleCourses)],
    },
  },
};

// No eligible round for this course: the panel renders nothing.
export const NotEligible: Story = {
  parameters: {
    msw: {
      handlers: [trpcStorybookMsw.facilitatorApplications.eligibleRounds.query(() => [])],
    },
  },
};
