/* DO NOT EDIT: this file was automatically generated by airtable-ts-codegen */
/* eslint-disable */
import { Item, Table } from 'airtable-ts';

export interface Person extends Item {
  id: string,
  email: string,
  firstName: string,
  lastName: string,
  ethnicGroup: string,
  careerPlans: string,
  biography: string,
  appliedToOpportunities: string[],
  isProfilePublic: boolean,
}

export const personTable: Table<Person> = {
  name: 'Person',
  baseId: 'appRcVrzrkGoSrfR4',
  tableId: 'tblA0UsJCiOt9MN0k',
  mappings: {
    email: 'fldJzIWg2HMBmwPjZ',
    firstName: 'fldxyoC98EoVQDrqa',
    lastName: 'fldrfvKXru0YEXLvh',
    ethnicGroup: 'fldaLQ2MnUVa9tdRf',
    careerPlans: 'fldqq4LyZ5pf26NsN',
    biography: 'fldg9GSGb1dY59kf4',
    appliedToOpportunities: 'fldhI1cqdvrXwbJb7',
    isProfilePublic: 'fldNW3O0U3vCBk0Nf',
  },
  schema: {
    email: 'string',
    firstName: 'string',
    lastName: 'string',
    ethnicGroup: 'string',
    careerPlans: 'string',
    biography: 'string',
    appliedToOpportunities: 'string[]',
    isProfilePublic: 'boolean',
  },
};

export interface Opportunity extends Item {
  id: string,
  title: string,
  organizationName: string,
  opportunitySummary: string,
  opportunityDescription: string,
  applicants: string[],
}

export const opportunityTable: Table<Opportunity> = {
  name: 'Opportunity',
  baseId: 'appRcVrzrkGoSrfR4',
  tableId: 'tblneFg0pOTRI3kfD',
  mappings: {
    title: 'fldEMP8VzGIUGD1l6',
    organizationName: 'fldpvKKPIODumUdfj',
    opportunitySummary: 'fldSJWSbDKXITt71D',
    opportunityDescription: 'fldO5FAmTx20HixOT',
    applicants: 'fldOCFhSNFqg12mjO',
  },
  schema: {
    title: 'string',
    organizationName: 'string',
    opportunitySummary: 'string',
    opportunityDescription: 'string',
    applicants: 'string[]',
  },
};