import type { Course } from '@bluedot/db';

export const mockCourse = (overrides: Partial<Course>): Course => ({
  averageRating: 4.5,
  cadence: 'Weekly',
  certificationBadgeImage: 'badge.png',
  certificationDescription: 'Certificate description',
  description: 'Course description',
  detailsUrl: 'https://example.com',
  displayOnCourseHubIndex: true,
  durationDescription: '4 weeks',
  durationHours: 40,
  id: 'course-id',
  image: '/images/courses/default.jpg',
  isFeatured: false,
  isNew: false,
  level: 'Beginner',
  path: '/courses/course-slug',
  publicLastUpdated: null,
  shortDescription: 'Short description',
  slug: 'course-slug',
  status: 'published',
  title: 'Course Title',
  units: [],
  ...overrides,
});
