name: Auto Label Priority
on:
  issues:
    types: [opened]

jobs:
  add-priority-label:
    if: contains(github.event.issue.body, 'Suggested Priority Level')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add priority label based on form selection
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body;
            
            // Extract the priority from the issue body
            // Looking for pattern like "Suggested Priority Level\n\nP2: Medium (Default)"
            const lines = body.split('\n');
            let priority = null;
            
            for (let i = 0; i < lines.length; i++) {
              if (lines[i].includes('Suggested Priority Level')) {
                // The selected value appears 2 lines after the label
                if (i + 2 < lines.length) {
                  const selectedLine = lines[i + 2];
                  // Extract P0, P1, P2, P3, or P4
                  const match = selectedLine.match(/^(P[0-4]):/);
                  if (match) {
                    priority = match[1];
                    break;
                  }
                }
              }
            }
            
            if (priority) {
              console.log(`Adding label: ${priority}`);
              
              // Add the priority label
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: [priority]
              });
            } else {
              console.log('No priority found in issue body');
            }
