name: Auto Label Priority
on:
  issues:
    types: [opened]

jobs:
  add-priority-label:
    if: contains(github.event.issue.body, 'Suggested Priority Level')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add priority label based on form selection
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body;
            
            // Extract priority (P0-P4) from dropdown selection
            const priorityMatch = body.match(/[{"]?(P[0-4])["}]?\s*=>/);
            
            if (!priorityMatch) {
              console.log('Priority not found in issue body');
              return;
            }
            
            const priority = priorityMatch[1];
            console.log(`Applying label: ${priority}`);
            
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: [priority]
            });
